<?php

return [
    'groups' => [
        'public' => [
            'welcome',
            'loginElectronica',
            'password.request',
            'about',
            'services',
            'pricing',
            'contact',
            'privacy',
            'terms',
            'login',
            'register',
            'contact.store',
        ],
        'auth' => [
            'dashboard',
            'home',
            'logout',
            'profile.edit',
            'profile.update',
            'profile.password',
            'profile.password.update',
            'profile.email',
            'profile.email.update',
            'profile.delete',
            'profile.two-factor',
            // Analytics
            'analytics.index',
            // Export/Import
            'export.index',
            'export.download',
            'import.store',
            // Roles
            'roles.index',
            'roles.create',
            'roles.store',
            'roles.show',
            'roles.edit',
            'roles.update',
            'roles.destroy',
            // Companies
            'companies.index',
            'companies.edit',
            'companies.update',
            // Employees/Users
            'employees_users.index',
            'employees_users.create',
            'employees_users.store',
            'employees_users.show',
            'employees_users.edit',
            'employees_users.update',
            'employees_users.destroy',
            // Orders
            'orders.index',
            'orders.create',
            'orders.store',
            'orders.show',
            'orders.edit',
            'orders.update',
            'orders.destroy',
            'orders.confirmPickup',
            'orders.pdf',
            'orders.documents.payment',
            'orders.documents.pickup',
            'orders.documents.delivery',
            // Reviews
            'orders.reviews.create',
            'orders.reviews.store',
            'reviews.show',
            'reviews.edit',
            'reviews.update',
            'reviews.destroy',
            // Customers
            'customers.index',
            'customers.create',
            'customers.store',
            'customers.show',
            'customers.edit',
            'customers.update',
            'customers.destroy',
            'customers.searchByDni',
            // Products
            'products.index',
            'products.create',
            'products.store',
            'products.show',
            'products.edit',
            'products.update',
            'products.destroy',
            // Payments
            'payments.index',
            'payments.create',
            'payments.store',
            'payments.show',
            'payments.edit',
            'payments.update',
            'payments.destroy',
            'payments.searchOrdersForPayment',
            // Support (para futuras implementaciones internas)
            'support.index',
            'support.create',
            'support.store',

            // Commissions
            'commissions.index',
            'commissions.payout',
        
        ],
    ],
];